//! Build script for claude-md-core
//!
//! Reads schema rules from YAML (Single Source of Truth) and generates
//! Rust constants at compile time.

use serde::Deserialize;
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

/// Section definition in schema-rules.yaml
#[derive(Debug, Deserialize)]
struct SectionDef {
    name: String,
    required: bool,
    #[serde(default)]
    condition: String,
    #[serde(default)]
    allow_none: bool,
}

/// Schema rules structure
#[derive(Debug, Deserialize)]
struct SchemaRules {
    #[allow(dead_code)]
    version: String,
    sections: HashMap<String, SectionDef>,
}

fn main() {
    // Path to schema rules YAML (relative to core/ directory)
    let schema_path = "../skills/schema-validate/references/schema-rules.yaml";

    // Tell Cargo to rerun if the schema file changes
    println!("cargo:rerun-if-changed={}", schema_path);

    // Read and parse the YAML file
    let yaml_content = fs::read_to_string(schema_path).unwrap_or_else(|e| {
        panic!(
            "Failed to read schema-rules.yaml at '{}': {}. \
             Make sure the file exists at plugins/claude-md-plugin/skills/schema-validate/references/schema-rules.yaml",
            schema_path, e
        )
    });

    let rules: SchemaRules = serde_yaml::from_str(&yaml_content).unwrap_or_else(|e| {
        panic!("Failed to parse schema-rules.yaml: {}", e)
    });

    // Extract required sections (where required=true and condition="always")
    let mut required_sections: Vec<&str> = rules
        .sections
        .values()
        .filter(|s| s.required && s.condition == "always")
        .map(|s| s.name.as_str())
        .collect();

    // Sort for consistent ordering
    required_sections.sort();

    // Extract sections that allow "None" as valid content
    let mut allow_none_sections: Vec<&str> = rules
        .sections
        .values()
        .filter(|s| s.allow_none)
        .map(|s| s.name.as_str())
        .collect();

    allow_none_sections.sort();

    // Generate Rust code
    let code = format!(
        r#"// Auto-generated by build.rs from schema-rules.yaml
// DO NOT EDIT MANUALLY - Edit skills/schema-validate/references/schema-rules.yaml instead

/// Required sections in CLAUDE.md (must always be present)
pub const REQUIRED_SECTIONS: &[&str] = &{:?};

/// Sections that allow "None" as valid content
pub const ALLOW_NONE_SECTIONS: &[&str] = &{:?};
"#,
        required_sections, allow_none_sections
    );

    // Write to OUT_DIR
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("schema_rules.rs");

    fs::write(&dest_path, code).unwrap_or_else(|e| {
        panic!("Failed to write generated code to {:?}: {}", dest_path, e)
    });

    println!("cargo:warning=Generated schema_rules.rs with {} required sections", required_sections.len());
}
